coverage:
  status:
    project:
      default:
        target: auto
        if_not_found: success
        against: master
    patch:
      default:
        target: auto
        if_not_found: success
