language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install .
    - pip install -r requirements-devel.txt
    - pip install python-coveralls
env:
    - PYTHONDONTWRITEBYTECODE=true
before_script:
    - rm  -rf tests/__init__.py
script:
    - py.test --assert=plain --cov=tests -v
after_success:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls -b bbarchivist -d .coverage -c .coveragerc
