language: python
dist: xenial
python:
    - "3.6"
    - "3.7"
addons:
    apt:
        packages:
            - p7zip-full
install:
    - pip install .
    - pip install -r requirements-devel.txt
    - pip install coverage
    - pip install codecov
    - pip install codeclimate-test-reporter
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip uninstall --yes defusedxml; fi
    - pip install scrutinizer-ocular
script:
    - py.test -v --cov=bbarchivist
after_success:
    - codecov
    - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter
    - ocular --data-file ".coverage" --config-file ".coveragerc"
