language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install .
    - pip install requests python-gnupg mock pytest httmock beautifulsoup4 shutilwhich
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install --upgrade git+https://github.com/pytest-dev/pytest.git; fi
env:
    - PYTHONDONTWRITEBYTECODE=true
script:
    - py.test --assert=plain
