language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - p7zip-full
install:
    - pip install .
    - pip install -r requirements-devel.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install coverage==3.7.1; else pip install coverage; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install coveralls=="1.0a2"; else pip install coveralls; fi
script:
    - py.test -v --cov=bbarchivist
after_success:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
