language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install .
    - pip install requests python-gnupg mock pytest httmock beautifulsoup4 progress shutilwhich
script:
    - py.test