language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "nightly"
matrix:
    allow_failures:
        - python: "3.7-dev"
        - python: "nightly"
addons:
    apt:
        packages:
            - p7zip-full
install:
    - pip install .
    - pip install -r requirements-devel.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install coverage=="3.7.1"; else pip install coverage; fi
    - pip install codecov
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install pytest=="2.9.2"; else pip install pytest; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then pip install codeclimate-test-reporter; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip uninstall --yes defusedxml; fi
    - pip install scrutinizer-ocular
script:
    - py.test -v --cov=bbarchivist
after_success:
    - codecov
    - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter; fi
    - ocular --data-file ".coverage" --config-file ".coveragerc"
