language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install .
    - pip install -r requirements-devel.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install coverage==3.7.1; else pip install coverage; fi
	- pip install coveralls
before_script:
    - rm  -rf tests/__init__.py
script:
    - py.test -v
after_success:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
