environment:
  matrix:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - cinst 7zip.commandline
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m pip install -r requirements-devel.txt"

build: off

test_script:
  - %PYTHON%\\python.exe -m pytest -v "

