environment:
  COVERALLS_REPO_TOKEN:
    secure: bYwUQ/6lG1y5LN0GW2s3Gshf08tT4N1CK0hbZAy6iYp+8dneIGdvxTsQ7Nf8giMe
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH="%PYTHON%";"%PYTHON%\Scripts";%PATH%
  - cinst 7zip.commandline
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m pip install -r requirements-devel.txt"
  - "%PYTHON%\\python.exe -m pip install coverage coveralls"

build: off

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

test_script:
  - "%PYTHON%\\python.exe -m pytest -v --cov=bbarchivist --cov-config .coveragerc tests/"
  - coveralls
