environment:
  CODECOV_TOKEN:
    secure: U/Icc3L/5XW50cUc/aui8k8eJauXjFVZL0rSbarLwASIyQc4yQpn5SJIbdtbBXRu
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH="%PYTHON%";"%PYTHON%\Scripts";%PATH%
  - cinst 7zip.commandline
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m pip install -r requirements-devel.txt"
  - "%PYTHON%\\python.exe -m pip install coverage codecov"

build: off

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

test_script:
  - "%PYTHON%\\python.exe -m pytest -v --cov=bbarchivist --cov-config .coveragerc tests/"
  - codecov --token=%CODECOV_TOKEN%
